export enum CursosEnum {
    ADM = "Administração",
    CIE_CONT = "Ciências Contábeis",
    DIR = "Direito",
    EDU_FIS = "Educação Física",
    ENF = "Enfermagem",
    ENG_AGRON = "Engenharia Agronômica",
    ENG_CIV = "Engenharia Civil",
    FARM = "Farmácia",
    FISIO = "Fisioterapia",
    JORN = " Jornalismo",
    LETR = " Letras",
    MEDIC = " Medicina",
    ODONT = " Odontologia",
    PEDAG = " Pedagogia",
    PSICO = " Psicologia",
    SERV_SOC = " Serviço Social",
    SIST_INF = " Sistema de Informação",
    TECN_AGRONEG = " Tecnólogo em Agronegócio",
    TECN_ESTE_COSM = " Tecnólogo Estética e Cosmética",
}